import Foundation
import InteropKit
import KnowledgeBaseWikiCore

/// 앱 상호운용 계약(docs/app-interop-contract.md) — {ok,result} 봉투로 자기소개.
/// ship-app.sh 의 register_interop 이 이걸 읽어 ~/.agent-apps/registry.json 에 등록한다.
/// 원장을 열지 않고 즉답(5초 타임아웃 호출).
private let wikiCommands: [Capabilities.Command] = [
            .init(name: "help", summary: "help|--help|-h: 원장 설정 없이 CLI 도움말 출력", json: false),
            .init(name: "version", summary: "CLI 버전 스탬프", json: false),
            .init(name: "publish", summary: "stdin 본문으로 새 객체 발행(append-only) → id", json: false),
            .init(name: "show", summary: "객체 출력(본문 포함)", json: false),
            .init(name: "status", summary: "원장 한 마디: world·객체 수·최근 발행", json: true),
            .init(name: "list", summary: "head 목록(--all 전체 역사)", json: true),
            .init(name: "search", summary: "키워드 조회(제목·태그·본문). --fleet 로 multi-world 랭킹", json: true),
            .init(name: "context", summary: "에이전트용 계층 컨텍스트 블록. --fleet 지원", json: false),
            .init(name: "path", summary: "두 객체 사이 인용 경로(BFS)", json: false),
            .init(name: "history", summary: "개정 계보(supersedes 사슬)", json: false),
            .init(name: "cited-by", summary: "역링크(이 객체를 인용한 것들)", json: false),
            .init(name: "verify", summary: "전 객체 무결성 검사(변조·참조·중복)", json: false),
            .init(name: "repository", summary: "agent-wiki repository summary [--path <repo>] --json", json: true),
            .init(name: "repository-summary", summary: "저장소 요약(repository 별칭)", json: true),
            .init(name: "task", summary: "new/handoff/bind/verify/done/knowledge-candidate/list: canonical repository task workflow", json: true),
            .init(name: "agent", summary: "run/sync/evolve/role — 저장소 역할 실행", json: false),
            .init(name: "agent run", summary: ".agents/roles 저장소 역할 실행; canonical task/runtime/dispatch worker_done 연동", json: false),
            .init(name: "agent role", summary: "저장소 담당 역할 list/create; .agents/roles 기계 SSOT", json: true),
            .init(name: "agent sync", summary: ".agents/roles 역할 정의를 append-only role-definition 이력과 동기화", json: false),
            .init(name: "run", summary: "agent run 하위명령(역할 실행)", json: false),
            .init(name: "sync", summary: "agent sync 하위명령(역할 정의 동기화)", json: false),
            .init(name: "evolve", summary: "agent evolve 하위명령", json: false),
            .init(name: "role", summary: "agent role 하위명령", json: true),
            .init(name: "chat", summary: "이 앱 맥락으로 에이전트에 질의", json: false),
            .init(name: "orchestration", summary: "task 어댑터(capsule/context/dispatch)", json: true),
            .init(name: "orchestration adapter",
                  summary: "explicit JSON/stdin Orca task/dispatch/worker_done/checker adapter; private-file scraping 없음",
                  json: true),
            .init(name: "orchestration capsule", summary: "deterministic bounded runtime/dispatch/knowledge/rules/stale/gate context", json: true),
            .init(name: "orchestration context", summary: "capsule과 동일한 machine-readable bounded context alias", json: true),
            .init(name: "promotion", summary: "agent-wiki promotion preview|publish <object-id> --to gujo [--confirm] --json", json: true),
            .init(name: "promote", summary: "promotion 별칭", json: true),
            .init(name: "recent", summary: "지식층 최근 변경 피드", json: false),
            .init(name: "changes", summary: "recent 별칭 — 최근 변경", json: false),
            .init(name: "world", summary: "세계관(독립 원장) 관리·전환", json: false),
            .init(name: "world rm", summary: "세계관 등록 제거(원장 디렉터리는 안 지움)", json: false),
            .init(name: "fleet", summary: "중앙 관제 레지스트리 list/doctor/scan/register (정본 아님)", json: true),
            .init(name: "pull", summary: "에이전트 스코프 pull — query/ids/event/blob 예산 적용", json: true),
            .init(name: "weight", summary: "에이전트별 world/domain 가중치 show|set", json: true),
            .init(name: "capabilities", summary: "이 자기소개 봉투", json: true),
            .init(name: "skill-install", summary: "coding-agent skills 부착 (~/.codex|claude|grok|agents)", json: true),
            .init(name: "skill-uninstall", summary: "이 앱이 붙인 skills 만 제거", json: true),
            .init(name: "skill-status", summary: "agent-wiki skill 부착 상태", json: true),
            .init(name: "skill", summary: "skill-install|uninstall|status 별칭", json: true),
            .init(name: "skills", summary: "skill 별칭", json: true),
            .init(name: "root", summary: "현재 world 원장 경로 출력", json: false),
            .init(name: "batch", summary: "작업 묶음 발급", json: false),
            .init(name: "classify", summary: "객체 분류", json: false),
            .init(name: "capture", summary: "수집 발행", json: false),
            .init(name: "rollback", summary: "묶음 되돌리기", json: false),
            .init(name: "policy", summary: "정책 조회·설정", json: false),
            .init(name: "structure", summary: "인용 구조 점검", json: false),
            .init(name: "migrate", summary: "원장 content-id 재주소화", json: false),
            .init(name: "checkpoint", summary: "체크포인트 발행", json: false),
            .init(name: "okf-export", summary: "OKF 내보내기", json: false),
            .init(name: "distill", summary: "원장 증류", json: false),
            .init(name: "review", summary: "검토 루프", json: false),
            .init(name: "tick", summary: "스케줄 틱 실행", json: false),
            .init(name: "backup", summary: "restic 야간 백업", json: false),
            .init(name: "index", summary: "파생 SQLite 인덱스 rebuild|sync|status", json: false),
            .init(name: "discuss", summary: "토론 발행", json: false),
            .init(name: "learn", summary: "경험칙 학습", json: false),
            .init(name: "metrics", summary: "learn 별칭", json: false),
            .init(name: "rules", summary: "규칙 조회", json: false),
            .init(name: "diff", summary: "객체 차이", json: false),
            .init(name: "blob", summary: "원본 blob 관리", json: false),
            .init(name: "event", summary: "사건 로그", json: false),
            .init(name: "graph", summary: "인용 그래프", json: false),
            .init(name: "app", summary: "원장 GUI 제어 표면", json: false),
]

public func runCapabilities() {
    let caps = Capabilities(
        name: "agent-wiki",
        version: LedgerVersion.current,
        cli: CommandLine.arguments[0],
        commands: wikiCommands,
        state: [.init(path: "~/.swift-app-state/memo-citation-ledger.json",
                      what: "활성 원장·canonical repoId·task/provenance 요약(관측성 미러 hook). 정본 키명은 memo-citation-ledger 로 보존")],
        health: .init(command: "agent-wiki verify", freshness: "~/.memo-citation-ledger/config.json"),
        owned: .init(depends: [
            .init(id: "system.curl", kind: Capabilities.DependencyKind.command, ref: "curl", required: true, why: "path in CommandPublish.swift"),
            .init(id: "system.ffmpeg", kind: Capabilities.DependencyKind.command, ref: "ffmpeg", required: true, why: "str in CommandPublish.swift"),
            .init(id: "cli.gujo", kind: Capabilities.DependencyKind.cli, ref: "gujo", required: false, why: "lit in main.swift"),
            .init(id: "system.launchctl", kind: Capabilities.DependencyKind.command,
                  ref: "launchctl", required: true, why: "path in CommandSchedule.swift"),
        ])
    )
    FileHandle.standardOutput.write((try? Envelope.ok(caps)) ?? Data())
    print("") // allow:debug
}
