import Foundation

/// Pure SwiftUI Emitter transforming PageSpec into clean, token-bound SwiftUI View code
public struct SwiftUIEmitter: Sendable {
    public init() {}

    public func emit(spec: PageSpec) -> String {
        let viewName = "\(sanitizedName(spec.slugAlias))PageView"
        let stateCases = spec.states.keys.sorted().map { "case \(sanitizedName($0))" }.joined(separator: "\n        ")

        return """
        //
        //  \(viewName).swift
        //  GujoEcosystem
        //
        //  Generated by PagePlanningKit (Swift 6 Native Emitter)
        //  Target: \(spec.targetEnvironment) (SSOT 1440px)
        //  UUID: \(spec.uuid)
        //

        import SwiftUI

        // MARK: - Page State Enum
        public enum \(sanitizedName(spec.slugAlias))State: String, CaseIterable, Sendable {
            \(stateCases)
        }

        // MARK: - Native View
        public struct \(viewName): View {
            @State private var currentState: \(sanitizedName(spec.slugAlias))State = .ready

            public init() {}

            public var body: some View {
                VStack(spacing: GujoSpacing.xLarge) {
                    headerSection
                    contentSection
                    recoverySection
                }
                .padding(GujoSpacing.canvasPadding)
                .frame(maxWidth: GujoSpacing.maxContentWidth)
                .background(GujoColor.background)
            }

            // MARK: - Header
            @ViewBuilder
            private var headerSection: some View {
                VStack(alignment: .leading, spacing: GujoSpacing.xSmall) {
                    HStack {
                        Text("\(spec.slugAlias)")
                            .font(.caption)
                            .fontWeight(.bold)
                            .padding(.horizontal, GujoSpacing.xSmall)
                            .padding(.vertical, GujoSpacing.xxSmall)
                            .background(GujoColor.badgeBg)
                            .foregroundColor(GujoColor.badgeText)
                            .cornerRadius(GujoSpacing.cornerRadiusSmall)

                        Spacer()

                        Text("State: \\(currentState.rawValue)")
                            .font(.caption2)
                            .foregroundColor(GujoColor.textMuted)
                    }

                    Text("\(spec.title)")
                        .font(.title)
                        .fontWeight(.bold)
                        .foregroundColor(GujoColor.text)

                    Text("\(spec.purpose)")
                        .font(.body)
                        .foregroundColor(GujoColor.textMuted)
                }
            }

            // MARK: - Content
            @ViewBuilder
            private var contentSection: some View {
                VStack(spacing: GujoSpacing.medium) {
                    ForEach(0..<\(max(1, spec.blocks.count)), id: \\.self) { idx in
                        RoundedRectangle(cornerRadius: GujoSpacing.cornerRadiusBase)
                            .fill(GujoColor.surface)
                            .overlay(
                                RoundedRectangle(cornerRadius: GujoSpacing.cornerRadiusBase)
                                    .stroke(GujoColor.surfaceBorder, lineWidth: 1)
                            )
                            .frame(height: 120)
                    }
                }
            }

            // MARK: - Recovery
            @ViewBuilder
            private var recoverySection: some View {
                if currentState != .ready {
                    HStack {
                        Text("Recovery Action Available")
                            .font(.subheadline)
                            .foregroundColor(GujoColor.warning)

                        Spacer()

                        Button("Recover to Ready") {
                            currentState = .ready
                        }
                        .buttonStyle(.borderedProminent)
                        .tint(GujoColor.primary)
                    }
                    .padding(GujoSpacing.medium)
                    .background(GujoColor.surface)
                    .cornerRadius(GujoSpacing.cornerRadiusBase)
                }
            }
        }
        """
    }

    private func sanitizedName(_ name: String) -> String {
        let cleaned = name.replacingOccurrences(of: "-", with: "_")
        let parts = cleaned.split(separator: "_")
        return parts.map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
    }
}
