import Foundation

/// Pure Web Emitter transforming PageSpec into clean, token-bound React TSX and Semantic HTML5
public struct WebEmitter: Sendable {
    public init() {}

    /// Emits a type-safe, token-bound React (TSX) Component
    public func emitTSX(spec: PageSpec) -> String {
        let componentName = "\(sanitizedName(spec.slugAlias))PageView"
        let stateUnion = spec.states.keys.sorted().map { "'\($0)'" }.joined(separator: " | ")
        let initialRecovery = spec.states["error"]?.recovery?.action ?? "retry"

        return """
        //
        //  \(componentName).tsx
        //  GujoEcosystem Web
        //
        //  Generated by PagePlanningKit (Swift 6 Native Web Emitter)
        //  Target: \(spec.targetEnvironment) (SSOT 1440px)
        //  UUID: \(spec.uuid)
        //

        import React, { useState } from 'react';

        export type \(sanitizedName(spec.slugAlias))State = \(stateUnion.isEmpty ? "'ready'" : stateUnion);

        export interface \(componentName)Props {
            initialState?: \(sanitizedName(spec.slugAlias))State;
            onAction?: (actionId: string) => void;
        }

        export const \(componentName): React.FC<\(componentName)Props> = ({
            initialState = 'ready',
            onAction
        }) => {
            const [currentState, setCurrentState] = useState<\(sanitizedName(spec.slugAlias))State>(initialState);

            const handleRecovery = () => {
                onAction?.('\(initialRecovery)');
                setCurrentState('ready');
            };

            return (
                <div className="gujo-canvas" data-target="PC-Desktop-1440" data-uuid="\(spec.uuid)">
                    <header className="gujo-page-header">
                        <div className="gujo-badge-cluster">
                            <span className="gujo-badge">\(spec.slugAlias)</span>
                            <span className="gujo-badge-sub">State: {currentState}</span>
                        </div>
                        <h1 className="gujo-title">\(escapeXml(spec.title))</h1>
                        <p className="gujo-purpose">\(escapeXml(spec.purpose))</p>
                    </header>

                    <main className="gujo-block-cluster">
                        \(spec.blocks.map { block in
                            """
                            <section className="gujo-block" data-block-id="\(block.id)" data-primitive="\(block.primitive)">
                                <h3 className="gujo-block-title">\(block.title ?? block.id)</h3>
                                <div className="gujo-block-body">\(escapeXml(block.description ?? ""))</div>
                            </section>
                            """
                        }.joined(separator: "\n                "))
                    </main>

                    {currentState !== 'ready' && (
                        <aside className="gujo-recovery-panel" role="alert">
                            <div className="gujo-recovery-message">Recovery Action Required for [{currentState}]</div>
                            <button
                                type="button"
                                className="gujo-button-primary"
                                onClick={handleRecovery}
                            >
                                Recover to Ready
                            </button>
                        </aside>
                    )}
                </div>
            );
        };

        export default \(componentName);
        """
    }

    /// Emits standalone, Zero-CSS token-bound Semantic HTML5
    public func emitHTML(spec: PageSpec) -> String {
        return """
        <!DOCTYPE html>
        <html lang="ko">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>\(escapeXml(spec.title)) - Gujo Planning</title>
            <link rel="stylesheet" href="../tokens.css">
        </head>
        <body class="gujo-body">
            <div class="gujo-canvas" data-target="PC-Desktop-1440" data-uuid="\(spec.uuid)">
                <header class="gujo-page-header">
                    <div class="gujo-badge-cluster">
                        <span class="gujo-badge">\(spec.slugAlias)</span>
                        <span class="gujo-badge-sub">Archetype: \(spec.archetype)</span>
                    </div>
                    <h1 class="gujo-title">\(escapeXml(spec.title))</h1>
                    <p class="gujo-purpose">\(escapeXml(spec.purpose))</p>
                </header>

                <main class="gujo-block-cluster">
                    \(spec.blocks.map { block in
                        """
                        <section class="gujo-block" data-block-id="\(block.id)" data-primitive="\(block.primitive)">
                            <h3 class="gujo-block-title">\(block.title ?? block.id)</h3>
                            <div class="gujo-block-body">\(escapeXml(block.description ?? ""))</div>
                        </section>
                        """
                    }.joined(separator: "\n            "))
                </main>
            </div>
        </body>
        </html>
        """
    }

    private func sanitizedName(_ name: String) -> String {
        let cleaned = name.replacingOccurrences(of: "-", with: "_")
        let parts = cleaned.split(separator: "_")
        return parts.map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
    }

    private func escapeXml(_ str: String) -> String {
        return str
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&apos;")
    }
}
